dist: trusty

sudo: required

language: python

python:
  - "3.5"

cache: pip

branches:
  only:
    - master

services:
  - docker

install:
  - git lfs pull -X dev/training_data.tar.gz
  - openssl aes-256-cbc -K $encrypted_6326f10f2b2b_key -iv $encrypted_6326f10f2b2b_iv -in
    secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar
  - pip install awscli
  - export IMAGE=$AWS_USER_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO
  - export LOGIN=$(aws ecr get-login --no-include-email)
  - eval $LOGIN
  - docker pull $IMAGE

script:
  - docker build . --cache-from $IMAGE --tag $IMAGE
  - docker push $IMAGE
  - CONTAINER=openears
  - ssh -o StrictHostKeychecking=no -i secrets/pi_rsa pi@$PI_IP -p $PI_PORT "eval $LOGIN &&
    docker pull $IMAGE && docker rm -f $CONTAINER || true && mkdir -p out &&
    docker run -d --restart always --name $CONTAINER --device /dev/snd -v /home/pi/out:/out $IMAGE"
